const defaultPlugins = [
  require("./aspectRatio"),
  require("./backgroundColor"),
  require("./borderColor"),
  require("./borderRadius"),
  require("./borderWidth"),
  require("./boxShadow"),
  require("./display"),
  require("./flex"),
  require("./fontFamily"),
  require("./fontSize"),
  require("./fontWeight"),
  require("./height"),
  require("./letterSpacing"),
  require("./lineHeight"),
  require("./margin"),
  require("./maxHeight"),
  require("./maxWidth"),
  require("./minHeight"),
  require("./minWidth"),
  require("./opacity"),
  require("./overflow"),
  require("./padding"),
  require("./position"),
  require("./rotate"),
  require("./scale"),
  require("./skew"),
  require("./systemColor"),
  require("./textColor"),
  require("./translate"),
  require("./width"),
  require("./zIndex"),
];

module.exports = defaultPlugins;
